#ifndef __SRC_MEM_PIM_PIM_MEM_CTRL_HH__
#define __SRC_MEM_PIM_PIM_MEM_CTRL_HH__

#include "mem/mem_ctrl.hh"
#include "params/PIMMemCtrl.hh" // This will be auto-generated by SCons

namespace gem5 {
namespace memory {

class PIMMemCtrl : public MemCtrl
{
  public:
    PIMMemCtrl(const PIMMemCtrlParams &p);

    // We override the main function that receives requests
    bool recvTimingReq(PacketPtr pkt) override;
    // void updateBlockedRead();

  protected:
    // Definition der MMIO-Register
    Addr pimBaseAddr;
    Addr pimRegSize  = pimBaseAddr + 0x00;
    Addr pimRegBytes = pimBaseAddr + 0x08;
    Addr pimRegCmd   = pimBaseAddr + 0x10;

    // Interne Speicherzellen für die abgefangenen Parameter
    uint64_t storedVectorSize;
    uint64_t storedElemBytes;

  private:
    // PacketPtr blockedResponsePack = nullptr;
    Tick pimReadyTick = 0;
};

} // namespace memory
} // namespace gem5

#endif // __SRC_MEM_PIM_PIM_MEM_CTRL_HH__
