#ifndef __SRC_MEM_PIM_PIM_MEM_CTRL_HH__
#define __SRC_MEM_PIM_PIM_MEM_CTRL_HH__

#include "mem/mem_ctrl.hh"
#include "params/PIMMemCtrl.hh" // This will be auto-generated by SCons

namespace gem5 {
namespace memory {

class PIMMemCtrl : public MemCtrl
{
  public:
    PIMMemCtrl(const PIMMemCtrlParams &p);

    // We override the main function that receives requests
    bool recvTimingReq(PacketPtr pkt) override;

  protected:
    // PIM trigger address
    Addr triggerAddr;
};

} // namespace memory
} // namespace gem5

#endif // __SRC_MEM_PIM_PIM_MEM_CTRL_HH__
