Import('*') # type: ignore

# Register the new SimObjects
# This creates params/PIMMemCtrl.hh and params/PIMDRAMInterface.hh headers
SimObject('PIMDRAMInterface.py', sim_objects=['PIMDRAMInterface']) # type: ignore
SimObject('PIMMemCtrl.py', sim_objects=['PIMMemCtrl']) # type: ignore

# This compiles the C++ and links it
Source('pim_dram_interface.cc') # type: ignore
Source('pim_mem_ctrl.cc') # type: ignore

# This enables the debug flag if you use DPRINTF(PIM, ...)
DebugFlag('PIM') # type: ignore
